name: CI

on: [push, pull_request]  # Lint et tests sur toutes les branches

env:
  TEST_IMAGE_NAME: app-test
  PROD_IMAGE_NAME: app-prod

jobs:
  lint:
    name: "Lint & Code Quality"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check PHP syntax
        run: find src -name "*.php" -exec php -l {} \;

      - name: PHP CS Fixer (dry-run)
        run: |
          if [ -f .php-cs-fixer.php ]; then
            vendor/bin/php-cs-fixer fix --dry-run --diff
          else
            echo "No PHP CS Fixer config found, skipping"
          fi

  build-test-image:
    name: "Build Test Image"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        run: docker build -t ${{ env.TEST_IMAGE_NAME }} .

      - name: Save test image
        run: docker save ${{ env.TEST_IMAGE_NAME }} > app-test.tar

      - name: Upload test image artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-test-image
          path: app-test.tar

  tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: build-test-image

    services:
      database:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: app_test
          MYSQL_USER: app
          MYSQL_PASSWORD: app
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test image
        uses: actions/download-artifact@v4
        with:
          name: app-test-image

      - name: Load test image
        run: docker load < app-test.tar

      - name: Wait for database
        run: |
          until nc -z localhost 3306; do
            echo "Waiting for database..."
            sleep 1
          done

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e APP_ENV=test \
            -e DATABASE_URL="mysql://app:app@localhost:3306/app_test" \
            -e JWT_PASSPHRASE="a9fbaa6f7c5f60a8944f21156c28abead68fc6fd9b59ceb859660971dc2f7c9f" \
            ${{ env.TEST_IMAGE_NAME }} \
            sh -c "
              mkdir -p config/jwt &&
              openssl genpkey -out config/jwt/private.pem -aes256 -pass pass:\$JWT_PASSPHRASE -algorithm RSA -pkeyopt rsa_keygen_bits:4096 &&
              openssl pkey -in config/jwt/private.pem -out config/jwt/public.pem -passin pass:\$JWT_PASSPHRASE -pubout &&
              php bin/console doctrine:database:create --if-not-exists &&
              php bin/console doctrine:migrations:migrate --no-interaction &&
              php bin/phpunit
            "

  build-prod-image:
    name: "Build Production Image"
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build production image
        run: |
          docker build \
            --build-arg APP_ENV=prod \
            --target production \
            -t ${{ env.PROD_IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Log in to registry (si tu veux push)
        # uses: docker/login-action@v3
        # with:
        #   registry: ghcr.io
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Login to registry here"

      - name: Push to registry (si tu veux push)
        # run: docker push ghcr.io/${{ github.repository }}/app:${{ github.sha }}
        run: echo "Push to registry here"