name: CI

on: [push, pull_request]  # Lint et tests sur toutes les branches

env:
  TEST_IMAGE_NAME: ${{ secrets.TEST_IMAGE_NAME }}
  PROD_IMAGE_NAME: ${{ secrets.PROD_IMAGE_NAME }}

jobs:
  lint:
    name: "Lint & Code Quality"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          tools: composer

      - name: Install dependencies
        run: composer install --no-progress --prefer-dist --optimize-autoloader

      - name: Check PHP syntax
        run: find src -name "*.php" -exec php -l {} \;

      - name: PHP CS Fixer (dry-run)
        run: |
          if [ -f .php-cs-fixer.php ]; then
            vendor/bin/php-cs-fixer fix --dry-run --diff
          else
            echo "No PHP CS Fixer config found, skipping"
          fi

  build-test-image:
    name: "Build Test Image"
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build test image
        run: docker build --no-cache --target test -t ${{ env.TEST_IMAGE_NAME }} .

      - name: Save test image
        run: docker save ${{ env.TEST_IMAGE_NAME }} > ${{ env.TEST_IMAGE_NAME }}.tar

      - name: Upload test image artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.TEST_IMAGE_NAME }}-image
          path: ${{ env.TEST_IMAGE_NAME }}.tar

  tests:
    name: "Run Tests"
    runs-on: ubuntu-latest
    needs: build-test-image

    services:
      database:
        image: postgres:15
        env:
          POSTGRES_DB: addict
          POSTGRES_USER: app
          POSTGRES_PASSWORD: addict
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download test image
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.TEST_IMAGE_NAME }}-image

      - name: Load test image
        run: docker load < ${{ env.TEST_IMAGE_NAME }}.tar

      - name: Wait for database
        run: |
          until nc -z localhost 5432; do
            echo "Waiting for database..."
            sleep 1
          done

      - name: Debug Docker image contents
        run: |
          echo "=== DEBUGGING DOCKER IMAGE CONTENTS ==="
          docker run --rm ${{ env.TEST_IMAGE_NAME }} sh -c "
            echo '1. Current directory:' && pwd &&
            echo '2. All files in root:' && ls -la &&
            echo '3. Tests directory:' && ls -la tests/ || echo 'NO tests directory' &&
            echo '4. Vendor directory exists:' && ls -ld vendor/ || echo 'NO vendor directory' &&
            echo '5. Vendor/bin contents:' && ls -la vendor/bin/ || echo 'NO vendor/bin directory' &&
            echo '6. Looking for phpunit anywhere:' && find . -name '*phpunit*' -type f 2>/dev/null || echo 'NO phpunit files found' &&
            echo '7. Composer show all packages:' && composer show | head -20 &&
            echo '8. Composer show phpunit specifically:' && composer show | grep phpunit || echo 'NO phpunit packages' &&
            echo '9. Check if symfony/phpunit-bridge exists:' && composer show symfony/phpunit-bridge || echo 'NO symfony/phpunit-bridge' &&
            echo '10. PHP version:' && php --version &&
            echo '11. Try to find phpunit executable:' && which phpunit || echo 'phpunit not in PATH' &&
            echo '12. Try different phpunit paths:' &&
            (php bin/phpunit --version 2>&1 || echo 'php bin/phpunit FAILED') &&
            (./vendor/bin/phpunit --version 2>&1 || echo './vendor/bin/phpunit FAILED') &&
            (vendor/bin/phpunit --version 2>&1 || echo 'vendor/bin/phpunit FAILED') &&
            echo '=== END DEBUG ==='
          "

      - name: Run tests
        run: |
          docker run --rm \
            --network host \
            -e APP_ENV=test \
            -e DATABASE_URL="postgresql://app:addict@localhost:5432/addict" \
            ${{ env.TEST_IMAGE_NAME }} \
            sh -c "
              php bin/console doctrine:database:drop --force --env=test || true &&
              php bin/console doctrine:database:create --env=test &&
              php bin/console doctrine:migrations:migrate -n --env=test &&
              php bin/console doctrine:fixtures:load -n --env=test &&
              php bin/phpunit --testdox
            "

  build-prod-image:
    name: "Build Production Image"
    runs-on: ubuntu-latest
    needs: tests
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build production image
        run: |
          docker build \
            --build-arg APP_ENV=prod \
            --target production \
            -t ${{ env.PROD_IMAGE_NAME }}:${{ github.sha }} \
            .

      - name: Log in to registry (si tu veux push)
        # uses: docker/login-action@v3
        # with:
        #   registry: ghcr.io
        #   username: ${{ github.actor }}
        #   password: ${{ secrets.GITHUB_TOKEN }}
        run: echo "Login to registry here"

      - name: Push to registry (si tu veux push)
        # run: docker push ghcr.io/${{ github.repository }}/${{ env.PROD_IMAGE_NAME }}:${{ github.sha }}
        run: echo "Push to registry here"